version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: ontop-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ontop
    ports:
      - '5433:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ontop.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8081:80'
    depends_on:
      - postgres

# --- Instructions ---
# To start the services in detached mode (background), run the following command in the project root:
# docker-compose up -d

# PostgreSQL Connection URL (for applications):
# jdbc:postgresql://localhost:5433/ontop