spring:
  application:
    name: challenge
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/ontop}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
